# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c83e408d551e8aa8cc41eebb57af38977e5bba6acefba727e4c79eae5b975d633f52bca4f8d5ae9387fc053d8847193318e2eae0d7c0bff17fa0a7346a81a41f

test:
  secret_key_base: 7e29f9d0ed1b5b485f8ffaa42b7cad0cd67ddd3c393fc8dd0e5c334a85e656384af89282d956093ac364a3df271c0782ca9123da46e72dd2d4c6d1a414e33f5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
